version: "3.1"
services:
  order-service:
    container_name: order-service
    build:
      dockerfile: Dockerfile
    volumes:
      - /app
    ports:
      - "8080:8080"
  #    depends_on:
  #      - common-contracts
