grpc:
  client:
    order-service:
      address: static://localhost:9091
      negotiationType: TLS
      security:
        trust-cert-collection: file:C:/Acuver-GIT/poc/case-study-kpl/grpc-case-study/common-contracts/src/main/ssl-tls/ca.cert.pem
server.port: 8080
#spring.sleuth.otel.exporter.otlp.endpoint: http://0.0.0.0:4317
#spring.sleuth.otel.config.trace-id-ratio-based: 1.0
#spring.application.name: ORDER-SERVICE

spring:
  data:
    mongodb:
      database: order
      host: localhost
      port: 27017


resilience4j:
  circuitbreaker:
    instances:
      defaultCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always