grpc:
  client:
    order-service:
      address: static://inventory-service:9091
      negotiationType: plaintext
server.port: 8080

spring.sleuth.otel.exporter.otlp.endpoint: http://0.0.0.0:4317
spring.sleuth.otel.config.trace-id-ratio-based: 1.0
spring.application.name: ORDER-SERVICE

spring:
  data:
    mongodb:
      database: order
      host: localhost
      port: 27017
