version: "3.1"
services:
  inventory-service:
    container_name: inventory-service
    build:
      dockerfile: Dockerfile
    volumes:
      - /app
    ports:
      - "8081:8081"
      - "9081:9081"
    links:
      - mongodb
#    depends_on:
#      - common-contracts